# Generated by Django 5.0.6 on 2024-07-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='image',
            field=models.ImageField(blank=True, upload_to='SkillsImage'),
        ),
    ]
